require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/wishers", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Wisher. As you add validations to Wisher, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Wisher.create! valid_attributes
      get wishers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      wisher = Wisher.create! valid_attributes
      get wisher_url(wisher)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_wisher_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      wisher = Wisher.create! valid_attributes
      get edit_wisher_url(wisher)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Wisher" do
        expect {
          post wishers_url, params: { wisher: valid_attributes }
        }.to change(Wisher, :count).by(1)
      end

      it "redirects to the created wisher" do
        post wishers_url, params: { wisher: valid_attributes }
        expect(response).to redirect_to(wisher_url(Wisher.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Wisher" do
        expect {
          post wishers_url, params: { wisher: invalid_attributes }
        }.to change(Wisher, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post wishers_url, params: { wisher: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested wisher" do
        wisher = Wisher.create! valid_attributes
        patch wisher_url(wisher), params: { wisher: new_attributes }
        wisher.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the wisher" do
        wisher = Wisher.create! valid_attributes
        patch wisher_url(wisher), params: { wisher: new_attributes }
        wisher.reload
        expect(response).to redirect_to(wisher_url(wisher))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        wisher = Wisher.create! valid_attributes
        patch wisher_url(wisher), params: { wisher: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested wisher" do
      wisher = Wisher.create! valid_attributes
      expect {
        delete wisher_url(wisher)
      }.to change(Wisher, :count).by(-1)
    end

    it "redirects to the wishers list" do
      wisher = Wisher.create! valid_attributes
      delete wisher_url(wisher)
      expect(response).to redirect_to(wishers_url)
    end
  end
end
