require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/wishes", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Wish. As you add validations to Wish, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Wish.create! valid_attributes
      get wishes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      wish = Wish.create! valid_attributes
      get wish_url(wish)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_wish_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      wish = Wish.create! valid_attributes
      get edit_wish_url(wish)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Wish" do
        expect {
          post wishes_url, params: { wish: valid_attributes }
        }.to change(Wish, :count).by(1)
      end

      it "redirects to the created wish" do
        post wishes_url, params: { wish: valid_attributes }
        expect(response).to redirect_to(wish_url(Wish.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Wish" do
        expect {
          post wishes_url, params: { wish: invalid_attributes }
        }.to change(Wish, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post wishes_url, params: { wish: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested wish" do
        wish = Wish.create! valid_attributes
        patch wish_url(wish), params: { wish: new_attributes }
        wish.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the wish" do
        wish = Wish.create! valid_attributes
        patch wish_url(wish), params: { wish: new_attributes }
        wish.reload
        expect(response).to redirect_to(wish_url(wish))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        wish = Wish.create! valid_attributes
        patch wish_url(wish), params: { wish: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested wish" do
      wish = Wish.create! valid_attributes
      expect {
        delete wish_url(wish)
      }.to change(Wish, :count).by(-1)
    end

    it "redirects to the wishes list" do
      wish = Wish.create! valid_attributes
      delete wish_url(wish)
      expect(response).to redirect_to(wishes_url)
    end
  end
end
